blog/apps/noticias/urls.py
from django.urls import path
from . import views
from .views import *


app_name = "noticias"

# urls de app noticias
urlpatterns = [
    path("", views.inicio, name= "inicio"),
     # url para el detalle de la noticia por pk
    path('detalle<int:pk>', views.Detalle_Noticias, name='detalle'),

    # url del formulario de contacto
    path('contacto', views.contacto, name="contacto"),

    # URL COMENTARIO
    path('comentario', views.Comentar_Noticia, name='comentar'),

    # urls comentarios
    path('<int:pk>/eliminar/', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('<int:pk>/editar/', views.Editcomentario.as_view(), name='comment_edit'),
    
    # urls noticias
    path('agregar_noticia', views.agregar_noticia, name='agregar_noticia'),
    path('<int:pk>/eliminar_noticia', views.eliminar_noticia, name='eliminar_noticia'),
    path('<int:pk>/editar_noticia', views.editar_noticia, name='editar_noticia'),

]

blog/apps/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [

    path('registro/', views.Registro.as_view(), name="registro"),

]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include                
from . import views

# URLS PARA LOGIN
from django.contrib.auth import views as auth
from django.conf.urls.static import static

from django.urls import reverse_lazy 
from django.conf import settings

# URL PRINCIPAL
urlpatterns = [
    path('admin/', admin.site.urls),
    # path para la view
    path("", views.home, name="home"),
    # path para nosotros
    path("nosotros/", views.nosotros, name="nosotros"),

    # ---------URL APP NOTICIAS------------------
    path("noticias/", include('apps.noticias.urls')),

    # # -----------URL LOGIN----------
    # path("usuarios/login",views.login, name="login")
    # path("login/", auth.LoginView.as_view(template_name= "usuarios/login.html"), name="login"),
    # path("logout/", auth.LoginView.as_view(), name= "logout"),
     # LOGIN
    # path('usuarios/login', views.login, name='login')
    path('login/', auth.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    # ultimo error de la clase solucionado
    # path('logout/', auth.LoginView.as_view(), name='logout'),
    # cambiar   LoginView por LogoutView
    path('logout/',auth.LogoutView.as_view() , name='logout'),


    # registro
    path("usuarios/", include("apps.usuarios.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #carga las imagenes de blog/media que son imagenes que se guardan en la BD

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>    
  <link rel="shotrcut icon" href="{% static 'img/cpu_icon_185103.png' %}"> 
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
      
    <link rel="stylesheet" href="{% static 'css/main.css'%}"> <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>Blog/ {% block titulo %} {% endblock titulo %}</title>
 </head> 
<!-- navbar  -->
<div>
    {% include "navbar.html" %}
</div>

<!-- <hr> -->
      
{% block contenido %} 

{% endblock contenido %}
<br>
<br>
<hr>


</div>



</body>

</html>

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}

{%block titulo%} HOME {%endblock titulo%}

{%block contenido%}
<h1 style="color: hsl(0, 100%, 25%); font-family: 'Calibri', sans-serif; font-size: 3em; font-weight: bold; text-decoration: underline;">CineCultura</h1>
<br>
<br>
<br>
<h2 style="color: hsl(0, 100%, 25%); font-family: 'Calibri', sans-serif;">¡BIENVENIDO AL MUNDO DEL CINE Y LA CULTURA!</h2>
    
</svg>
</svg>
<br>
<br>
    
  <p><img src= {% static 'img/im.jpg' %} alt="error" height="370px"></p>
  <br>
  <br>
  <h1 style="color: hsl(0, 100%, 25%); font-family: 'Calibri', sans-serif";> Este es el inicio de nuestro Blog</h1>

<br>
<br>

{% endblock contenido %}
  

blog/templates/navbar.html
<header
    class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <div class="col-md-3 mb-2 mb-md-0">
        <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
            <svg class="bi" width="40" height="32" role="img" aria-label="Bootstrap">
                <use xlink:href="#bootstrap"></use>
            </svg>
        </a>
    </div>
    <!-- CASITA -->
     <ul class="nav col-0 col-md-left mb-2 justify-left-start mb-md-0 ">
    <li class="nav-item">  
        <li  id="icono-izquierda" ><a class="nav-link" href="{% url 'home' %}" style="color: #ff0000;"><h3>Inicio<svg xmlns=BLANCO width="32" height="32" fill="currentColor" class="bi bi-cpu" viewBox="0 0 16 16">
            <path d="."/>
            </svg></a>
            </li>
        </ul> 
    
    <!-- endCASITA -->
    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        
        <li class="nav-item">
            
            <a class="nav-link instagram-link" target="_blank "href="https://www.instagram.com/Jordan_Nichiporuk/"><svg xmlns="" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
               <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
             </svg></a>            
        
             
        
             <li class="nav-item square-item">
                <a href="{% url 'noticias:inicio' %}" class="nav-link px-2" style="color: rgb(255, 0, 13);">Noticias</a>
            </li>
            <li class="nav-item square-item">
                <a href="{% url 'nosotros' %}" class="nav-link px-2" style="color: rgb(255, 0, 13);">Nosotros</a>
            </li>
            <li class="nav-item square-item">
                <a href="{% url 'noticias:contacto' %}" class="nav-link px-2" style="color: rgb(255, 0, 13);">Contacto</a>
            </li>
        </ul>

    <div class="col-md-3 text-end">
        {% if user.is_authenticated %}
            Bienvenido {{ user.username }}
            <button type="button" class="btn btn-primary"><a class="nav-link" href="{% url 'logout' %}">Cerrar
            sesion</a></button>
        {% else %}
            <button type="button" class="btn btn-outline-primary me-2"><a class="nav-link" href="{% url 'login' %}"> iniciar
                sesion</a></button>
            <button type="button" class="btn btn-outline-primary me-2"><a class="nav-link"
                href="{% url 'usuarios:registro' %}">Registrar</a></button>
        {% endif %}
    </div>
</header>

blog/templates/nosotros.html
{% extends 'base.html' %}
{% load static %}

{%block titulo%} NOSOTROS {%endblock titulo%}

{% block contenido %}
<h1>Objetivo del blog</h1>
<p>Este blog se ha creado con la intención de ofrecer a los usuarios información precisa, interesante y actualizada sobre el fascinante mundo del cine y la cultura. Nos enfocamos en proporcionar reseñas de películas, noticias relevantes del mundo del entretenimiento, análisis de tendencias cinematográficas, cobertura de festivales, debates sobre temas culturales y mucho más. Nuestro objetivo es ser una fuente confiable y completa para los amantes del cine y aquellos interesados en explorar la diversidad cultural a través del arte cinematográfico.</p>
<hr>
<h1>Abarca temas como:</h1>
<p>Reseñas de películas</p>
<p>Noticias de entretenimiento</p>
<p>Análisis de tendencias cinematográficas</p>
<p>Cobertura de festivales</p>
<p>Debates sobre temas culturales</p>
<p>Y mucho más...</p>

<hr>
<div class="col-lg-12">

    <article >
        <div class="container" data-aos="fade-up">
          <div class="row">
            <div class="col-12 text-center mb-2">
              <div class="row justify-content-center">
                <div class="col-lg-12">
                  <h2 class="display-4" id="posicion" style="color: #e91c1c;">Nuestro equipo</h2>
                  <p id="posicion" style="color: #aa1e1e;">Nuestro grupo conformado por, Nichiporuk Jordan Agustin, Mauricio Maximiliano Galarza Mora ,llevamos a cabo este proyecto con tematica Cine y Cultura </p>
                </div>
              </div>
            </div>
            <div id="posicion2" class="col-lg-6 text-center mb-0">
              <img src="assets/img/person-1.jpg" alt="" class="img-fluid rounded-circle w-50 mb-4">
              <h4 style="color: #e91c1c;">Nichiporuk,Jordan Agustin</h4>
              
            </div>
            <div id="posicion2" class="col-lg-6 text-center mb-0">
              <img src="assets/img/person-2.jpg" alt="" class="img-fluid rounded-circle w-50 mb-4">
              <h4 style="color: #e91c1c;">Mauricio Maximiliano Galarza Mora</h4>
              

            </div>
          </div>
        </div>
    </article>
  
{%endblock contenido%}    