blog/apps/noticias/urls.py
from django.urls import path
from . import views
from .views import *


app_name = "noticias"

# urls de app noticias
urlpatterns = [
    path("", views.inicio, name= "inicio"),
     # url para el detalle de la noticia por pk
    path('detalle<int:pk>', views.Detalle_Noticias, name='detalle'),

    # url del formulario de contacto
    path('contacto', views.contacto, name="contacto"),

    # URL COMENTARIO
    path('comentario', views.Comentar_Noticia, name='comentar'),

    # urls comentarios
    path('<int:pk>/eliminar/', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('<int:pk>/editar/', views.Editcomentario.as_view(), name='comment_edit'),
    
    # urls noticias
    path('agregar_noticia', views.agregar_noticia, name='agregar_noticia'),
    path('<int:pk>/eliminar_noticia', views.eliminar_noticia, name='eliminar_noticia'),
    path('<int:pk>/editar_noticia', views.editar_noticia, name='editar_noticia'),

]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include                
from . import views

# URLS PARA LOGIN
from django.contrib.auth import views as auth
from django.conf.urls.static import static

from django.urls import reverse_lazy 
from django.conf import settings

# URL PRINCIPAL
urlpatterns = [
    path('admin/', admin.site.urls),
    # path para la view
    path("", views.home, name="home"),
    # path para nosotros
    path("nosotros/", views.nosotros, name="nosotros"),

    # ---------URL APP NOTICIAS------------------
    path("noticias/", include('apps.noticias.urls')),

    # # -----------URL LOGIN----------
    # path("usuarios/login",views.login, name="login")
    # path("login/", auth.LoginView.as_view(template_name= "usuarios/login.html"), name="login"),
    # path("logout/", auth.LoginView.as_view(), name= "logout"),
     # LOGIN
    # path('usuarios/login', views.login, name='login')
    path('login/', auth.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    # ultimo error de la clase solucionado
    # path('logout/', auth.LoginView.as_view(), name='logout'),
    # cambiar   LoginView por LogoutView
    path('logout/',auth.LogoutView.as_view() , name='logout'),


    # registro
    path("usuarios/", include("apps.usuarios.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #carga las imagenes de blog/media que son imagenes que se guardan en la BD

blog/apps/noticias/models.py
from django.db import models
from apps.usuarios.models import Usuario
# Create your models here.


class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.nombre


class Noticia(models.Model):
    titulo = models.CharField(max_length=150)
    cuerpo = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='noticias')
    categoria_noticia = models.ForeignKey(Categoria, on_delete=models.CASCADE)


    def __str__(self) -> str:
        return self.titulo


class Contacto(models.Model):
    nombre = models.CharField(max_length=60)
    correo = models.EmailField()
    asunto = models.CharField(max_length=40)
    texto = models.TextField()

    def __str__(self) -> str:
        return self.nombre


class Comentario(models.Model):
    texto = models.TextField(null=True)
    fecha = models.DateTimeField(auto_now_add=True)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.noticia} {self.texto}"

blog/apps/noticias/forms.py
from django import forms
from .models import Contacto, Noticia


class ContactoForm(forms.ModelForm):

    class Meta:
        model = Contacto
        fields = "__all__"


class NoticiaForm(forms.ModelForm):

    class Meta:
        model= Noticia
        fields = "__all__"

blog/apps/noticias/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Noticia, Categoria, Contacto, Comentario
# Create your views here.

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin  

from .forms import ContactoForm, NoticiaForm
# importamos reverse lazy para los comentarios
from django.urls import reverse_lazy

from django.db.models import Q 

# decorador para ver las noticias solamente como usuario logueado
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View


# uso de decorador para verificar logeo de usuario y poder ver noticia
# @login_required
def filtrar_noticia(fecha, orden, contexto):
    if fecha == 'asc':
        noticias = Noticia.objects.all().order_by('fecha')
        contexto['noticias'] = noticias

    elif fecha == 'des':
        noticias= Noticia.objects.all().order_by('-fecha')
        contexto['noticias'] = noticias


    if orden == 'asc':
        noticias = Noticia.objects.all().order_by('titulo')
        contexto['noticias'] = noticias

    elif orden == 'des':
        noticias = Noticia.objects.all().order_by('-titulo')
        contexto['noticias'] = noticias
    return contexto

def inicio(request):
    contexto = {}
    queryset = request.GET.get("buscar") 
    fecha = request.GET.get('fecha')
    orden = request.GET.get('orden')
    if queryset:
        n = Noticia.objects.filter(
            Q(titulo__icontains = queryset) |
            Q(cuerpo__icontains = queryset) |
            Q(categoria_noticia__nombre = queryset)
        ).distinct().order_by('-fecha')[0:2]

        filtrar_noticia(fecha, orden, contexto)['noticias'] = n

        return render(request, 'noticias/inicio.html',contexto)
    else:
        id_categoria = request.GET.get('id', None)
        if id_categoria:
            n = Noticia.objects.filter(categoria_noticia=id_categoria).order_by('-fecha')
     

        else:
            n = Noticia.objects.all().order_by('-fecha') # una lista
        filtrar_noticia(fecha, orden, contexto)['noticias'] = n
        cat = Categoria.objects.all()
        filtrar_noticia(fecha, orden, contexto)['categorias'] = cat
        return render(request, 'noticias/inicio.html', contexto)


# @login_required
def Detalle_Noticias(request, pk):
    contexto = {}

    n = Noticia.objects.get(pk=pk)
    contexto['noticia'] = n

   

    c = Comentario.objects.filter(noticia=n)
    contexto['comentarios'] = c

    return render(request, 'noticias/detalle.html', contexto)


# ClaseName.objects.all()[0:2]              select * from noticias
# ClaseName.objects.get(pk = 1)        select * from noticias where id = 1
# ClaseName.objects.filter(categoria)  select * from noticias where categoria = deportes


def contacto(request):
    data = {
        'form': ContactoForm()
    }
    if request.method == 'POST':
           ContactoForm(data=request.POST).save()

    return render(request, 'contacto/formulario.html', data)


@login_required
def Comentar_Noticia(request):
    comentario = request.POST.get('comentario', None)
    user = request.user
    noti = request.POST.get('id_noticia', None)
    noticia = Noticia.objects.get(pk=noti)
    coment = Comentario.objects.create(
        usuario=user, noticia=noticia, texto=comentario)
    return redirect(reverse_lazy('noticias:detalle', kwargs={"pk": noti}))


# creando las clases que me permiten modificar y elimiar los comentarios
class Editcomentario(View):
    def get(self, request, pk):
        comment = Comentario.objects.get(pk=pk) # extraemos el objeto de comentarios con igual pk
        noticia = comment.noticia 
        return render(request, 'noticias/edit.html', {'comment': comment, 'noticia': noticia})

    def post(self, request, pk):
        comment = Comentario.objects.get(pk=pk)
        nuevo_contenido = request.POST.get('texto')
        comment.texto = nuevo_contenido
        comment.save()
        noticia = comment.noticia      # buscamos de que noticia es el comentario para sarlo para redireccionarme a la misma despues de editarla
        return redirect('noticias:detalle', pk=noticia.pk)



class CommentDeleteView(View):
    def get(self, request, pk):
        comment = get_object_or_404(Comentario, pk=pk) # comprobamos si el usuaro que va a borrarlo es el mismo que quien creó el comentario, para mandarlo al html de delete
        noticia = comment.noticia
        if comment.usuario == request.user:
            return render(request, 'noticias/delete.html', {'comment': comment, 'noticia': noticia})
        else:
            noticia = comment.noticia  # sinó lo redireccionamos de nuevo
            return redirect('noticias:detalle', pk=noticia.pk) 

    def post(self, request, pk):
        comment = get_object_or_404(Comentario, pk=pk)
        if comment.usuario == request.user: # si el usuario es el que creó el comentario este se borra
            if request.method == 'POST':
                comment.delete()
        noticia = comment.noticia
        return redirect('noticias:detalle', pk=noticia.pk)  

# agregar, eliminar, editar y filtrar noticias
def agregar_noticia(request):
    if request.method == 'POST':
        form = NoticiaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('noticias:inicio')
    else:
        form = NoticiaForm()

    return render(request, 'noticias/formulario.html', {'form': form})
  



def eliminar_noticia(request, pk):
    noticia = Noticia.objects.get(pk =pk)
    noticia = get_object_or_404(Noticia, pk=pk)
    contexto = {'noticia': noticia}
    if request.method == 'POST':
        noticia.delete()
        return redirect('noticias:inicio')
    return render(request, 'noticias/deletenoticia.html', contexto)

 


def editar_noticia(request, pk):
    # obtengo la noticia y si no existe tira error
    noticia = get_object_or_404(Noticia, pk=pk)
    # si se aprieta el boton de guardar cambios manda la info a travez de POST 
    if request.method == 'POST':
        # inicializamos el formulario con el parametro instance, que es un parametro que se necesita para actualizar una instancia de la BD
        form = NoticiaForm(request.POST, instance=noticia)
        if form.is_valid():
            form.save()
            return redirect('noticias:detalle', pk=noticia.pk) 

    else:
        form = NoticiaForm(instance=noticia)
   
    return render(request, 'noticias/editnoticia.html',{'form': form, 'noticia': noticia})

blog/templates/noticias/delete.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}

<h1>Eliminar Comentario</h1>
<br>
<p>¿Enserio quieres eliminar este comentario?</p>
<p>{{ comment.texto }}</p>
    <form method="post">
        {% csrf_token %}
        <br>
        <div><input type="submit" value="Eliminar">  <button type="button" class="btn btn-primary"><a class="nav-link" href="{% url 'noticias:detalle' noticia.pk %}">Cancelar y volver</a></button></div>
    </form>


{% endblock contenido %}

blog/templates/noticias/deletenoticia.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}

<h1>Eliminar Noticia</h1>
<br>
<p>¿Enserio quieres eliminar esta noticia?</p>
<h4><p>{{ noticia.titulo }}</p></h4>
    <form method="post">
        {% csrf_token %}
        <br>
        <div><input type="submit" value="Eliminar">  <button type="button" class="btn btn-primary"><a class="nav-link" href="{% url 'noticias:detalle' noticia.pk %}">Cancelar y volver</a></button></div>
    </form>
</body>
</html>

{% endblock contenido %}

blog/templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block titulo%}Noticia{%endblock titulo%}

{% block contenido%}

{% if user.is_superuser or user.is_staff %}
    <button type="button" class="btn btn-primary"><a class="nav-link" href="{% url 'noticias:editar_noticia' noticia.pk %}"> editar noticia</a></button>
    <hr>
{% endif %}

<h1>{{noticia}}</h1>
<img src="{{noticia.imagen.url}}" alt="" width="300">
<p class="color">{{noticia.cuerpo}}</p>

<p>{{noticia.fecha}}</p>
<p>{{noticia.categoria_noticia}}</p>



<br>
<hr>


{% if user.is_authenticated %}
<h3>Comentá algo aquí</h3>
<form action="{% url 'noticias:comentar' %}" method="post">{% csrf_token %}

    <textarea name="comentario" cols="30" rows="3"></textarea>
    <input type="text" name="id_noticia" value="{{ noticia.pk }}" hidden="">
    <input type="submit" value="comentar">
</form>


<br>
<hr>


    <h3>Comentarios</h3>
    {% for com in comentarios %}
    <div class="contenedor">
    <div class="row mb-2">
    <div class="col-md-16">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-8 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary-emphasis">{{ com.usuario }} 
                </strong>
                <h3 class="mb-0"><strong> comentario: {{ com.texto }}</strong></h3>
                <div class="mb-1 text-body-secondary"> {{ com.fecha }}</div>

            {% if user == com.usuario or user.is_superuser or user.is_staff %}
            <a class="dropdown-item" href="{% url 'noticias:comment_edit' com.pk %}">Editar</a>
            <a class="dropdown-item" href="{% url 'noticias:comment_delete' com.pk %}">Eliminar</a>
            {% endif %}
            </div>
        </div>
        <title>Placeholder</title>
    {% endfor %}
    </div>
    </div>
    </div>

     
<hr>


    {% if user.is_superuser or user.is_staff %}
        <button type="button" class="btn btn-outline-primary me-2"><a class="nav-link" href="{% url 'noticias:eliminar_noticia' noticia.pk %}"> eliminar noticia</a></button>
    {% endif %}
    
{% else %}
    <h3>¿Quieres comentar y ver las opiniones de los demás?</h3> 
    <h2> LOGEATE </h2>
    <button type="button" class="btn btn-primary"><a class="nav-link" href="{% url 'login' %}?next={{ request.path }}"> iniciar
    sesion</a></button>
{% endif %}


{% endblock contenido %}

blog/templates/noticias/edit.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}

<h1>Editar Comentario</h1>
<br>
<form method="post">
    {% csrf_token %}
    <textarea name="texto" rows="4" cols="50">{{ comment.texto }}</textarea>
    <br>
    <div><input type="submit" value="Guardar cambios">  <button type="button" class="btn btn-primary"><a class="nav-link" href="{% url 'noticias:detalle' noticia.pk %}">Cancelar y volver</a></button></div>
</form>


{% endblock contenido %}

blog/templates/noticias/editnoticia.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}

<h1>Editar Noticia</h1>
<br>
 <form method="post">
    <br>
    {% csrf_token %}
    {{ form.as_p }}
    <br>
    <div> <input type="submit" value="Guardar cambios">  <button type="button" class="btn btn-primary"><a class="nav-link" href="{% url 'noticias:detalle' noticia.pk %}">Cancelar y volver</a></button></div>
    
</form>

{% endblock contenido %}

blog/templates/noticias/formulario.html
{% extends 'base.html' %}
{% load static %}

{% block titulo%} Noticias {%endblock titulo%}

{% block contenido%}
<h1>Agregar Noticia</h1>
<br>
{{ form.errors }}
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}<!-- el  enctype="multipart/form-data" es para admsitir el envío de archivos o imagenes, que se estan incluyendo en el formulario -->
    {{ form.as_p }}
    <br>
    <div><input type="submit" value="Publicar noticia"> <button type="button" class="btn btn-primary"><a class="nav-link" href="{% url 'noticias:inicio' %}">Cancelar y volver</a></button></div>
</form>

{% endblock contenido%}

blog/templates/noticias/inicio.html
{% extends 'base.html' %}
{% load static %}

{% block titulo%} noticias {% endblock titulo %}

{% block contenido%}


      
<aside>
    <div class="p-4">
        <h3 class="fst-italic">Categorias</h3>
        <ol class="list-unstyled mb-0">

            <li><a href="{% url 'noticias:inicio' %}" style="color: #ff0000;"> Todas</a></li>
            <li>{% for c in categorias %}
                <a href="?id={{c.pk}}" style="color: #ff0000;">{{c.nombre}}</a>
                {% endfor %}
            </li>
        </ol>
    </div>
    </div>
</aside>
</div>
{% block barra_busqueda %}

    <div class="container">

        <div class="row height d-flex justify-content-center align-items-center">

          <div class="col-md-6">
            <form method="get">

                <div class="form">
                  <i class="fa fa-search"></i>
                  <input type="text" class="form-control form-input" placeholder="Buscar..." name = "buscar" value = "{{ request.GET.buscar }}">
                  <span class="left-pan"></i></span>
                </div>
            </form>
          </div>

        </div>

      </div>
{% endblock barra_busqueda %}
{% if user.is_superuser or user.is_staff %}

    <hr>
    <button type="button" class="btn btn-primary"><a class="nav-link" href="{% url 'noticias:agregar_noticia' %}"> Agregar Noticia</a></button>

{% endif %}


<hr>

<a href="{% url 'noticias:inicio' %}?fecha=asc " style="color: #ff0000;">Más antiguas</a>

<a href="{% url 'noticias:inicio' %}?fecha=des " style="color: #ff0000;">Más actuales</a>

<a href="{% url 'noticias:inicio' %}?orden=asc " style="color: #ff0000;">De A a Z</a>

<a href="{% url 'noticias:inicio' %}?orden=des " style="color: #ff0000;">De Z a A</a>

<hr>

{% for noticia in noticias %}
    <div class="contenedor">
    <div class="row mb-2">
        <div class="col-md-16">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-8 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary-emphasis">{{noticia.categoria_noticia}}</strong>
                    <h3 class="mb-0"><strong>{{ noticia.titulo }}</strong></h3>
                    <div class="mb-1 text-body-secondary">{{noticia.fecha}}</div>
                    <p class="card-text mb-auto">{{ noticia.cuerpo|slice:250 }}...</p>
                    <a href="{% url 'noticias:detalle' noticia.pk %}"
                        class="icon-link gap-1 icon-link-hover stretched-link" style="color: #ffffff;" >
                        Seguir leyendo...
                        <svg class="bi">
                            <use xlink:href="#chevron-right"></use>
                        </svg>
                    </a>
                </div>
                <div class="col-auto d-none d-lg-block">
                    <img class="bd-placeholder-img" src="{{ noticia.imagen.url }}" width="400" height="250"
                        xmlns="" role="img" aria-label="Placeholder: Thumbnail"
                        preserveAspectRatio="xMidYMid slice" focusable="false">

                    <title>Placeholder</title>

                </div>

            </div>
        </div>
    </div>
</div>
{% endfor %}


<!-- boton de subida -->
<hr>

  <button  id="btnVolverArriba" width="52" height="52" class="btn btn-primary" style="color: #ffffff;" > Volver arriba</button>

  <script>
    // Obtener el botón y el evento scroll
    const btnVolverArriba = document.getElementById('btnVolverArriba');
    window.addEventListener('scroll', () => {
        if (window.pageYOffset > 100) {
            // Mostrar el botón cuando el desplazamiento sea mayor a 100px
            btnVolverArriba.style.display = 'block';
        } else {
            // Ocultar el botón cuando el desplazamiento sea menor o igual a 100px
            btnVolverArriba.style.display = 'none';
        }
    });


     // Función para volver arriba cuando se hace clic en el botón
    btnVolverArriba.addEventListener('click', () => {
        window.scrollTo({
            top: 0,
            behavior: 'smooth' // Desplazamiento suave (smooth)
        });
    });


    </script>


{% endblock contenido%}